# Generated by Django 5.0.3 on 2024-03-08 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeOfDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('correct_answer_description', models.TextField()),
                ('marks', models.IntegerField()),
                ('negative_marks', models.IntegerField(blank=True, null=True)),
                ('name_of_exam', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_exam', models.CharField(blank=True, max_length=4, null=True)),
                ('subject_of_exam', models.CharField(blank=True, max_length=255, null=True)),
                ('question_numbering_exam_paper', models.IntegerField(blank=True, null=True)),
                ('sub_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('repeat_in_exam', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('applicability', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_of_difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_module.degreeofdifficulty')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions_module.questiontype')),
            ],
        ),
    ]
