# Generated by Django 5.0.3 on 2024-03-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('Matching', 'Matching'), ('Koat', 'Koat'), ('Statement_Reason', 'Statement & Reason'), ('Fill_in_the_blank', 'Fill in the blank')], max_length=20)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('correct_answer_description', models.TextField()),
                ('marks', models.IntegerField()),
                ('negative_marks', models.IntegerField()),
                ('name_of_exam', models.CharField(max_length=255)),
                ('year_of_exam', models.CharField(max_length=4)),
                ('subject_of_exam', models.CharField(max_length=255)),
                ('question_numbering_exam_paper', models.IntegerField()),
                ('sub_topic', models.CharField(max_length=255)),
                ('repeat_in_exam', models.CharField(max_length=255)),
                ('other', models.CharField(max_length=255)),
                ('degree_of_difficulty', models.CharField(max_length=255)),
                ('applicability', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
