# Generated by Django 5.0.3 on 2024-03-08 06:36

# import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0001_initial'),
    ]

 
