# Generated by Django 5.0.3 on 2024-03-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0002_alter_question_correct_answer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
