# Generated by Django 5.0.3 on 2024-03-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0004_alter_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
    ]
