# Generated by Django 5.0.3 on 2024-03-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0006_alter_question_option_b_alter_question_option_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
