# Generated by Django 5.0.3 on 2024-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0009_alter_question_option_a_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='questions_module.keyword'),
        ),
    ]
