# Generated by Django 5.0.3 on 2024-03-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='exam',
            new_name='exam_category',
        ),
        migrations.RemoveField(
            model_name='area',
            name='description',
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_manager.area')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_manager.part')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_manager.topic')),
            ],
        ),
    ]
