# Generated by Django 5.0.3 on 2024-03-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0003_remove_syllabus_content_syllabus_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='content',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default=1, upload_to='BookFiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(default=1, upload_to='NotesFiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='file',
            field=models.FileField(default=1, upload_to='QuestionBankFiles'),
            preserve_default=False,
        ),
    ]
